### ISSUE TITLE
Order pre-assembled boards

### ISSUE THREAD

**Issue by dmazzella** [gbr1/portenta_h7_repin#1]
Hi Giovanni,
where can I buy 2 or 3 (preferably pre-assembled)?

Thank you,
D.

**Comment by gbr1** [comment]
Hi! Thanks for your interest. I'm trying to understand the best way to starting selling them. If you need asap, please write me an email

**Comment by gbr1** [comment]
I was able to create a small batch of repin!
Check them out here:
https://tinyurl.com/repin-1

Thank you!

@gmacario @dmazzella
